### ISSUE TITLE
install bcrypt error: Undefined variable module_name in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by MadShura** [kelektiv/node.bcrypt.js#876]
I'm already having the correct dependencies 
python 2.7 
VS2017
OS: window10  version:2004 
when type npm install bcrypt still throw sth wrong.
how can i do?

here is the err msg:
PS C:\Users\AXL\Desktop\tieba\gaopudaimaApi> npm install bcrypt
npm ERR! code 1
npm ERR! path C:\Users\AXL\Desktop\tieba\gaopudaimaApi\node_modules\bcrypt
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.4 | win32 | x64
npm ERR! gyp info find Python using Python version 2.7.0 found at "D:\python 2.7\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.28307.1525) found at:
npm ERR! gyp info find VS "D:\vscode\c++"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn D:\python 2.7\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\Desktop\\tieba\\gaopudaimaApi\\node_modules\\bcrypt\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\AppData\\Local\\node-gyp\\Cache\\14.15.4\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\AXL\\AppData\\Local\\node-gyp\\Cache\\14.15.4',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\AXL\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\AXL\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.15.4\\\\<(target_arch)\\\\node.lib',npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\AXL\\Desktop\\tieba\\gaopudaimaApi\\node_modules\\bcrypt',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\Desktop\\tieba\\gaopudaimaApi\\node_modules\\bcrypt\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\AXL\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "D:\\node\\node.exe" "C:\\Users\\AXL\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\AXL\Desktop\tieba\gaopudaimaApi\node_modules\bcrypt
npm ERR! gyp ERR! node -v v14.15.4
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AXL\AppData\Local\npm-cache\_logs\2021-05-20T20_50_41_119Z-debug.log

**Comment by MadShura** [comment]
waiting your reply. save me pls

**Comment by arbourd** [comment]
Fixed this with updating `node-pre-gyp`.

`npm rm bcrypt` `npm i bcrypt`

**Comment by MadShura** [comment]
thank arbourd ! @arbourd 
but is not work
here is the list: is still throw same error: Undefined variable module_name in binding.gyp while trying to load binding.gyp

PS C:\Users\AXL\Desktop\tieba\gaopudaimaApi> npm install @mapbox/node-pre-gyp -g

changed 56 packages in 2s
PS C:\Users\AXL\Desktop\tieba\gaopudaimaApi> npm rm bcrypt   

up to date in 2s

56 packages are looking for funding
  run `npm fund` for details
PS C:\Users\AXL\Desktop\tieba\gaopudaimaApi> npm i bcrypt
npm ERR! code 1
npm ERR! path C:\Users\AXL\Desktop\tieba\gaopudaimaApi\node_modules\bcrypt
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.4 | win32 | x64
npm ERR! gyp info find Python using Python version 2.7.0 found at "D:\python 2.7\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.28307.1525) found at:
npm ERR! gyp info find VS "D:\vscode\c++"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn D:\python 2.7\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\Desktop\\tieba\\gaopudaimaApi\\node_modules\\bcrypt\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\AppData\\Local\\node-gyp\\Cache\\14.15.4\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\AXL\\AppData\\Local\\node-gyp\\Cache\\14.15.4',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\AXL\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\AXL\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.15.4\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\AXL\\Desktop\\tieba\\gaopudaimaApi\\node_modules\\bcrypt',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\AXL\\Desktop\\tieba\\gaopudaimaApi\\node_modules\\bcrypt\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\AXL\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! gyp ERR! command "D:\\node\\node.exe" "C:\\Users\\AXL\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"    
npm ERR! gyp ERR! cwd C:\Users\AXL\Desktop\tieba\gaopudaimaApi\node_modules\bcrypt
npm ERR! gyp ERR! node -v v14.15.4
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AXL\AppData\Local\npm-cache\_logs\2021-05-22T11_03_34_088Z-debug.log

**Comment by arbourd** [comment]
So another work around is using `npm 6` over `npm 7`.

You could also delete your local npm cache `npm cache clean --force` and then reinstall bcrypt.

The issue is related directly to npm 7 and packages using an outdated `node-pre-gyp` or `node-gyp`

**Comment by MadShura** [comment]
i don't know why but when use yarn add bcrypt , is work!
thank you @arbourd

**Comment by arbourd** [comment]
Probably because it changed the node-pre-gyp 😁

**Comment by MadShura** [comment]
> So another work around is using `npm 6` over `npm 7`.
> 
> You could also delete your local npm cache `npm cache clean --force` and then reinstall bcrypt.
> 
> The issue is related directly to npm 7 and packages using an outdated `node-pre-gyp` or `node-gyp`
> 
> What version of `node-pre-gyp` is in your `package-lock.json`?

may be is the npm cache problem ,but im no sure 
thank you @arbourd
